### ISSUE TITLE
Duplicate messages using JdbcTableListener

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/iaf#1528]
**Describe the bug**

**Reporter**
Mouli

**Category** 
Use following Tags to categorize your bug report
 - Frank Console
 - Frank Framework
 - Ladybug (debugging tool) --> This project has it's own repository. Please report issues in [ibissource/ibis-ladybug](https://github.com/ibissource/ibis-ladybug/issues)
 - Larva (unit test tool)
 - Performance

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty]
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge]
 - IAF Version: [e.g. 7.5, 7.6]

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Moulib1978** [comment]
**Problem 1 :** 
Before we had expectation that when we will have retries done in case something went wrong, it shouldn't retry.  
But it  was retrying even when we provide maxretries=0.  
To solve this problem we replaced JdbcQueryListener to JdbcTableListener with maxRetries=0 and we removed transactionAttribute=Required in the code. 
**This problem is solved**. After this change in code now it is not retrying when there is something wrong.

**Problem 2 :**
Now we get retries done when nothing went wrong. The retries done, in case nothing went wrong, is causing duplicate processing. This needs to be solved.

**Observation for problem 2 :** 
It's not happening on every message so we assume there's some timing / locking issue which causes this.
We assume that something with the update to "**in process**" query is wrong. It seems,  currently it's doing:
UPDATE OUTPUTSET SET OUTPUTSET_STATUS = 2 WHERE OUTPUTSET_ID = 12345
While we would expect that it does something like
UPDATE OUTPUTSET SET OUTPUTSET_STATUS = 2 WHERE OUTPUTSET_ID = 12345 and OUTPUTSET_STATUS = 1
Then based on the outcome of that query (0 or 1 updates done) the process can know if it did update the record and therefore is allowed to process it.
         <JdbcTableListener 
		name="EngageoneTraxBuilderDatabaseListener"
		tableName="OUTPUTSET"
		datasourceName="jdbc/ibis4oma" 
		keyField="OUTPUTSET_ID"
		statusField="OUTPUTSET_STATUS"
		statusValueAvailable="1"
		statusValueError="4"
		statusValueProcessed="3"
		statusValueInProcess="2"
		selectCondition="OUTPUTSET_TYPE='ENGAGEONE'"
	/>
