### ISSUE TITLE
Statsfile IJA_Tibet2 gets extremely large on DEV (repeat of #1062)

### ISSUE THREAD

**Issue by githubapreinders** [ibissource/iaf#1565]
Describe the bug
Statsfile IJA_Tibet2 gets extremely large on DEV

Reporter
Ap

Category
Performance

Go to 'https://srdzzapp*******/ija_tibet2/iaf/gui/#!/logging'
See file: ija_tibet2_stats_.......it becomes extremely large in size. Have seen it being 4GB ; after a deploy on DEV it starts growing rapidly. Screenshot shows the size after a fresh deploy and after removing all the older stats-files.
Problems arise for example when deploying new versions.
Expected behavior
A normal file size of the stats files. I have not seen the behaviour on TST with version 7.5-RC3

This problem has been attempted to solve with issue #1062. Where 5GB extra memory was added (that was past october). Now the problem seems to repeat itself.

**Comment by gvanbrakel** [comment]
ija_tibet2 appears to write every minute to the stats log.
We decided to remove the big log files, and restart to be able to analyse what is going on.

**Comment by gvanbrakel** [comment]
The growing of the stats log file appears to be related to the CheckReload job (that runs every minute).
If the CheckReload job is paused, the stats log does not grow anymore.

**Comment by gvanbrakel** [comment]
Lines like the following appear every minute in ija_tibet2.log:
```
2021-03-12 17:53:11,046 INFO [CheckReload[scheduler_Worker-1]] null scheduler.JobDef - Job [CheckReload] configuration [main] with version [8-96260c55-master_20201130-1624] will be reloaded with new version [8-96260c55]
2021-03-12 17:53:11,047 INFO [CheckReload[scheduler_Worker-1]] null scheduler.JobDef - Job [CheckReload] configuration [applicationclaim] with version [7-92b58c37-master_20200828-1232] will be reloaded with new version [92b58c37-master]
```

This means these two configurations are tried to be reloaded every minute. As part of the reload, the adapter is stopped, and the statistics are dumped to the stats.log

The problem appears to me that the version in the database table differs from the version of the configuration that is loaded from the database.

I can think of two work-arounds:
1) stop the CheckReload job
2) adjust the versions in the database table, so that they reflect the actual version of the configurations that they represent.

proper solution would be to make sure that these versions match when the configuration is uploaded to the database.

**Comment by gvanbrakel** [comment]
After upgrade to 7.5.1 stats files appear to be of normal size again
