### ISSUE TITLE
Restrict which attributes developers can set on FrankElements

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#1883]
**Describe the issue**
I noticed that the configuration element contains the following attributes:
```
<xs:attribute name="autoStart" type="frankBoolean"/>
<xs:attribute name="unloadInProgressOrDone" type="frankBoolean"/>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="version" type="xs:string"/>
<xs:attribute name="originalConfiguration" type="xs:string"/>
<xs:attribute name="loadedConfiguration" type="xs:string"/>
<xs:attribute name="validating" type="frankBoolean"/>
<xs:attribute name="configLocation" type="xs:string"/>
<xs:attribute name="beanName" type="xs:string"/>
<xs:attribute name="allowBeanDefinitionOverriding" type="frankBoolean"/>
<xs:attribute name="allowCircularReferences" type="frankBoolean"/>
<xs:attribute name="id" type="xs:string"/>
<xs:attribute name="displayName" type="xs:string"/>
<xs:attribute name="className" type="xs:string" fixed="nl.nn.adapterframework.configuration.Configuration" use="prohibited"/>
```

The only attributes that developers may use are `name`, `version` and `autoStart`. 

I'd like to see a javadoc tag that we can set on attributes to exclude them

**Reporter**
Niels

**Comment by gvanbrakel** [comment]
Could even use a tag that excludes the attributes of a superclass or interface.

**Comment by mhdirkse** [comment]
I already made a filter that excludes parents. I expect that enabling this filter is enough.

**Comment by nielsm5** [comment]
#1888 partially fixes this issue

**Comment by gvanbrakel** [comment]
I suggest (or agree with the same idea presented by others) to create java annotation to:
- suppress the inclusion of  specific setters
- suppress the inclusion of setters specified by a specific interface

**Comment by mhdirkse** [comment]
What if the interface we want to exclude is third-party? The wrapper API filters the ClassDoc objects using an include filter and an exclude filter. The include filter only keeps objects having a package name starting with "nl.nn.adapterframework" or "nl.nn.ibistesttool". When some of our Java classes implements an interface from a non-matching package, then we won't see the inheritance.

I see the following ways to deal with this:
* We can change the include filter for the wrapper API (FrankElementFilters.java) to include some third-party packages. Then the classes and interfaces in these package are visible by the wrapper API. We can make an another annotation, say @DontInheritFrankAttributesFrom. We place that annotation on Java classes of which we maintain the source. The argument of the annotation lists names of inherited interfaces from which the methods will not produce Frank attributes.
* Say we have a class F that appears as an element in the Frank!Doc. Say that it implements a third-party interface T from which we dont want to have Frank attributes. We can create an interface "I" ourselves that extends T. Then F implements "I", not T directly. Now we can put an annotation @NoFrankAttributes on "I" to ensure that the methods of T dont become attributes. The methods in interface "I" can have @Override annotations so we can test that the methods of "I" are indeed methods of T. We don't test that methods in T are also in "I".

Niels, can you give a few examples of attributes we want to suppress? That makes discussing this issue easier. And are there also config children we need to suppress?

**Comment by mhdirkse** [comment]
About the example of MessageStoreSender. It extends JdbcTransactionalStorage. JdbcTransactionalStorage implements ITransactionalStorage. I found the following methods in ITransactionalStorage:

```
public void setSlotId(String string);
public void setType(String string);
```

These methods are implemented in JdbcTransactionalStorage and these implementations are inherited by MessageStoreSender. I heard that methods inherited from JdbcTransactionalStorage can become attributes and also that setSlotId() should not produce an attribute because we want to suppress inheritance from ITransactionalStorage.

I have the following understanding now. Methods that are not in ITransactionalStorage but that are in JdbcTransactinalStorage can produce attributes for MessageStoreSender. JdbcTransactionalStorage for example has the method

```
public void setDateFieldType(String string)
```
This method is not in ITransactionalStorage, so MessageStoreSender has attribute `dateFieldType`. Methods that are both in ITransactionalStorage and JdbcTransactionalStorage don't produce attributes. Even though `setSlotId` appears in ITransactionalStorage and is implemented in JdbcTransactionalStorage. there is no attribute slotId in MessageStoreSender.

**Comment by nielsm5** [comment]
Yes, that is correct. However, if there is another interface which implements the same method, the MessageStoreSender (in this example) **_should_** produce an attribute.
A simple `ignore all methods defined in a 'hidden' interface` won't do.

**Comment by mhdirkse** [comment]
Clear. Thanks.

**Comment by nielsm5** [comment]
#2136
