### ISSUE TITLE
LocalFileSystemPipe does not recognize charset automatically

### ISSUE THREAD

**Issue by ricardovh** [ibissource/iaf#2707]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The LocalFileSystemPipe does not recognize ANSI/Windows-1252 charset automatically, while Notepad does recognize it for the attached file. When explicitly setting charset="Windows-1252" the LocalFileSystemPipe can read the file correctly with its diacritics.

**Reporter**
Ricardo

**Configuration**
```
<module>	
	<adapter name="Repro">
		<receiver name="Repro">
			<listener name="Repro" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline firstPipe="Repro">
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro"
				className="nl.nn.adapterframework.pipes.LocalFileSystemPipe"
				action="read">
				<forward name="success" path="EXIT" />
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Additional Context**
[ANSI.txt](https://github.com/ibissource/iaf/files/7993500/ANSI.txt)

**Comment by nielsm5** [comment]
Misschien een mooi moment om de icu te LCM-en en daar gebruik van te maken (of iets van http://www.java2s.com/Code/Java/I18N/Howtoautodetectafilesencoding.htm)

**Comment by gvanbrakel** [comment]
It might be enough to extend/fix `StreamUtil.getCharsetDetectingInputStreamReader()`

**Comment by gvanbrakel** [comment]
*Operation of charset argument*

Charset arguments can be used when producing or consuming binary Messages.


When producing binary messages (Base64 decode, read a file, multipart HTTP request), the a charset property is stored under the key Metadata.Charset in the MessageContext,
if the message is known or expecte to represent encoded character data. In some cases the charset is determinable from the source, e.g. in HTTP part messages where it might 
specified in the content-type header. We will refer to this value as the KnownCharset. If the KnownCharset cannot be determined, the value of the value of this charset property 
can be controlled using the charset attribute on the object that creates the binary message. 

||Attribute value||resulting charset property under Metadata.Charset if KnownCharset is null or empty||
|null, or empty string|none|
|charsetname (e.g. 'ISO-8859-1')|the charset name specified|
|auto|try to determine the charset from BOM or first part of stream. If found with sufficient confidence, that value is set, otherwise it is set to 'auto-unknown', signifying an attempt to determine it has been made but did not succeed|


When consuming binary messages as characters, a character set is required to convert the binary data into characters. This character set is determined as follows:
1) the value of the charset property stored under key Metadata.Charset in the MessageContext, if this is not 'auto-unknown';
2) the value of charset attribute specified on the object that is consuming the message. The value of this attribute may be 'auto', see below for procedure.
3) the default character set UTF-8

procedure charset value 'auto' when consuming messages.
If the value of the charset attribute is 'auto':
- if the value of the charset property stored under key Metadata.Charset is not equal to 'auto-unknown', then the
  charset is determined from BOM or first part of the stream. If not found with sufficient confidence, a warning is issued, and UTF-8 is used.
- if the value of the charset property stored under key Metadata.Charset is equal to 'auto-unknown', then a warning is issued, and UTF-8 is used.
