### ISSUE TITLE
As a developer I'd like to be able to see the raw reply message in the log files

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#5145]
Currently, there is no log for the response message that is returned to the caller in the log files. It would be really nice to see the raw response message with all available properties in the message as a log line in the log files. 

Ladybug improvement to be able to see the properties/metadata(e.g. Jms headers) would be nice as well.

**Reporter**
Ali

**Comment by jkosternl** [comment]
Hi @alisihab, I've added logging on several locations in the JMS classes. I've improved some extra code around it as well. 
Can you verify if this is what you wished for, while creating this issue? Otherwise, please give specific locations where you would like to have more logging. 

Thanks!
Jacobjob
