### ISSUE TITLE
Role Based Authentication voor API listener

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#557]
**Is your feature request related to a problem? Please describe.**
In the Api listener we want to implement fine grained authorization per API endpoint (operation). 

**Describe the solution you'd like**
The user/pwd combination on the API endpoint will be validated against the LDAP, fine grained validation needs to be implemented without creating multiple the roles in the ibis.
 
**Describe alternatives you've considered**
functionality created based on default Frank Components  

**Additional context**
Part of the SOAP/Rest POC

**Comment by nielsm5** [comment]
If you set the attribute `authenticationMethod="AUTHROLE"` and `authenticationRoles="IbisTester,myCustomRole"` you can limit access to a specific endpoint through application server provided roles.
In order to add custom roles to your endpoint use the property: `servlet.ApiListenerServlet.securityroles="myCustomRole"`
