### ISSUE TITLE
Issues with Json2XmlValidatorPipe : Cannot form request XML if child element is passed in URL GET request

### ISSUE THREAD

**Issue by pswapnil1987** [ibissource/iaf#559]
**Describe the bug**
In the adapter we are passing params to Json2XmlValidatorPipe which we receive in our URL, and then Json2XmlValidatorPipe creates the request XML by mapping those params to XSD elements with same name and validates it. This works fine for all the elements but fails with child element. Child element is not mapped in the request.

**Category**
 - Frank Framework

**To Reproduce**
1. Create an adapter with ApiListener listening to GET request.
2. In the pipeline, put Json2XmlValidatorPipe as first pipe and feed in the XSD with elements having child elements. Also, map URL parameter to child element in XSD.
3. Now send this parameter via GET URL and make a call on API endpoint.
4. Check request XML created and look out for this child element in request.

**Expected behavior**
URL parameter should be mapped to child element but then we also need to take care of scenario where 2 child elements with same name would be present under different parent elements.

**Environment:**
 - Application server  : Tomcat
 - IAF Version : 7.5-RC2

**Comment by gvanbrakel** [comment]
Jeroen, Swapnil,

Could you please supply an XSD, a configuration and a request url, and attach those to the issue?

Thanks,

Gerrit

Van: pswapnil1987 <notifications@github.com>
Verzonden: dinsdag 31 maart 2020 14:57
Aan: ibissource/iaf <iaf@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ibissource/iaf] Issues with Json2XmlValidatorPipe : Cannot form request XML if child element is passed in URL GET request (#559)


Describe the bug
In the adapter we are passing params to Json2XmlValidatorPipe which we receive in our URL, and then Json2XmlValidatorPipe creates the request XML by mapping those params to XSD elements with same name and validates it. This works fine for all the elements but fails with child element. Child element is not mapped in the request.

Category

  *   Frank Framework

To Reproduce
Steps to reproduce the behavior:

  1.  Create an adapter with ApiListener listening to GET request.
  2.  In the pipeline, put Json2XmlValidatorPipe as first pipe and feed in the XSD with elements having child elements. Also, map URL parameter to child element in XSD.
  3.  Now send this parameter via GET URL and make a call on API endpoint.
  4.  Check request XML created and look out for this child element in request.

Expected behavior
URL parameter should be mapped to child element but then we also need to take care of scenario where 2 child elements with same name would be present under different parent elements.

Environment:

  *   Application server : Tomcat
  *   IAF Version : 7.5-RC2

**Comment by pswapnil1987** [comment]
[#559.zip](https://github.com/ibissource/iaf/files/4412460/559.zip)

Attached requested files to issue. In this example, maxItems element is child element of Paging in XSD. We have mapped it as a param in configuration but is not included in created request.

**Comment by gvanbrakel** [comment]
solution to this is to set an additional attribute
deepSearch="true"
