### ISSUE TITLE
Backslash in vault files is not supported by the framework

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#5590]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have a vault file with a password having a backslash char. When I run a unit test in credentialprovider module pointing to my vault file, I am getting the following error:

![image](https://github.com/ibissource/iaf/assets/10929856/8ac267d7-2279-4f75-8fe6-fae96b2e748e)

For now, I used the unicode representation of the backslash and that seems to work but of course that is not the preferred solution.

**Reporter**
Ali

FF: 7.9-20230811.190015

**Comment by nielsm5** [comment]
We should look at all Properties.load(InputStream) methods and replace them as done in #4480.

**Comment by tnleeuw** [comment]
The username/passwords in the vault file are read as property-files and for Java property files, that just appears to be the way they work.

I added the `charsetDetectingInputstreamReader` as done in the referenced PR, forced a vault file which has a password with a `\u` with single backslash, and cannot make the error go away.

If Java writes the property file to string, it will automatically insert a double `\\` instead of a single `\`, because that is the property file spec.

You can also infer this from the stacktrace, which gives the error in the property loading code and not in the input stream reading code!

Sorry that this cannot be fixed with the current design of the credential-provider. You will have to use double backslashes.
