### ISSUE TITLE
False alarm in Frank!Console

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/iaf#622]
**Describe the bug**
I have a Frank configuration with a DirectoryListener. When I use the Frank!Console to stop the adapter that contains it, the Frank!Console produces the following warning message: "WARNING: receiver currently in state [Stopping], ignoring stop() command". This warning message is counted in configuration summary panel and it is visible in the configuration messages panel. I would expect operators to be very keen on messages showing up in this important place. I think this is a false alarm that should not appear this way.

**Category**
 - Frank Console

**To Reproduce**
 - Install the Frank!Runner, working with `classes`, `configurations` and `tests`.
- In `classes`, make an empty configuration to define the standard `<jmsRealm>` `jdbc/${instance.name.lc}`.
- Put the [NewHorizons.zip](https://github.com/ibissource/iaf/files/4510041/NewHorizons.zip) configuration in `configurations`.
- Start the Frank!Runner with the following command: `start.bat -Djdbc.migrator.active=true -Dwork=work`
- Stop adapter "adapterGetDestinations".

**Expected behavior**
When you stop an adapter and nothing goes wrong, no error message and warning message should appear in the configuration summary and configuration messages panels.

**Screenshots**
![image](https://user-images.githubusercontent.com/6784732/79868249-ed46b080-83df-11ea-8f9c-c56e70118584.png)

**Environment:**
 - Frank!Runner
 - Microsoft Edge
 - IAF 7.6-20200421.142707

**Additional context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Hi,

When I tested your configuration I noticed that the receiver failed to start because the (input?)folder did not exist on my local machine. We recently fixed an issue where, when in error, you would indeed get this alarm. So to my knowledge it should be already fixed. I've also colored the receivers in error state in red. So it's easier to know/realize something is wrong.

As for the `WARNING: receiver currently in state [Stopping], ignoring stop() command`
Could you try this again with the latest version of the Frank!Framework?

**Comment by mhdirkse** [comment]
This issue has not been fixed. I tested it again with Frank!Framework version 7.6-20200527.081219. Can you reopen this issue?

The example config given with this issue needs a directory `work` as a child of your frank-framework directory. This `work` directory needs subdirectories `input`, `processing`, `processed` and `error`.

**Comment by mhdirkse** [comment]
Verified. Thanks.
